projects:
  awsecommerce:
    schemaPath: amplify/backend/api/awsecommerce/build/schema.graphql
    includes:
      - src/amplify-graphql/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/amplify-graphql
        region: ap-south-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
